name: Python to EXE and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Get short commit hash
        id: get_short_sha
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $env:GITHUB_ENV

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed --add-data "assets;assets" --add-data "data;data" main.py -n snake-water-gun

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snake-water-gun-exe
          path: dist/snake-water-gun.exe

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.SHORT_SHA }}
          name: "Release ${{ env.SHORT_SHA }}"
          files: dist/snake-water-gun.exe
